#This config is made to get a reliable data transfer with a 100MBit/s Ethernet Interface

#Set ROS publishing rate - independet from the actual frame rate of the camera (it adjust dynamically)
frame_rate: 20.0

#Activate Downsampling and set the size of the generated voxels in meter. (0.05 = 5cm)
#This is helpful to reduce the bandwith in the network or to limit the data comming to your algorithm afterwards
downsampling: true
downsampling_voxel_size: 0.03

#Enable or Disable the projected range or/and intensity image
range_image: true
intensity_image: true